eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
server:
  port: 8060
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/LiYe107/spring-cloud/
          search-paths: neau-config
          force-pull: true
          #username: LiYe107
          #password: springcloud
