spring:
  zipkin:
    base-url: http://localhost:8070
  sleuth:
    sampler:
      percentage: 1.0
  application:
    name: iron-man-service
server:
  port: 8071
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka  
