spring:
  zipkin:
    base-url: http://localhost:8070
  sleuth:
    sampler:
      percentage: 1.0
  application:
    name: soar-service
server:
  port: 8072
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka  
  